### ISSUE TITLE
Log out of windows and then log in to windows will cause an error

### ISSUE THREAD

**Issue by ChuangHoward902** [bitraker/SteelSeriesScreenSync#3]
just reported a problem. When I press win+L to log out and log in to Windows, Windows will start to flash, indicating that the memory is almost used up, but the RAM usage rate is only 30%. After a while, Windows will display an error about the memory. The error reports are different every time but it's all about of the memory problem. I have to restart the computer to solve this problem. (I closed all other programs, only Steelseries and screensync is running)

**Comment by bitraker** [comment]
Okay, that was odd. On my Windows 10 machine the program consumes 30MB memory right now. Can you look in the Task Manager and report the memory consumption of the program?

Also what is your system memory capacity?

**Comment by ChuangHoward902** [comment]
I have 32gb memory, screensync doesn't consume too much resources on my computer, but as soon as I log out and back in, it triggers a bug that causes the whole windows to start flickering, and then shows that the memory is about to run out, but I think it's just a bug  Caused by it, because when he came up with the memory running out notification, I still had a lot of space in ram, and then I couldn't start any programs, until finally there would be an error, but it was different every time

These are the last error notifications that will appear:

An exception occurred in the application unknown software exception (0x40000015) at location
 0x00007FF962B7B15C,
 Please click (OK) to terminate the program, please click (Cancel) for program debugging

______
dwm corruption

______
logonui.exe error

**Comment by bitraker** [comment]
Do you have any strange messages in the application.log file, leading up to this issue, that is created by screensync?

The issue is truly odd to me, because the program is very simple and doesn't interfere with much.

I dont believe its the communication with the SteelSeries local API that causes this.

So it must somehow be the sampling of pixels on the screen, that annoys Windows and causes a strange behaviour.

Are you running Windows 11? 

I have had some weird issues with memory with Windows 11 happen with 32GB on my system as well and low utilization. 

This caused me to downgrade (reinstall) to Windows 10 which removed the problem. But this issue was not related to screensync, but games in general.

Does the problem go 100% away if you dont launch the screensync application at all?

**Comment by ChuangHoward902** [comment]
okay I know what the problem is, it should be my windows 11 problem, because I have no problems with other win 11 computers, I should reinstall windows and it will be fine
